"""Shared helpers for client/server coordination."""

from .axis_spec import (  # noqa: F401
    AxisExtent,
    AxisRole,
    AxisSpec,
    WorldSpan,
    axis_by_index,
    axis_by_label,
    axis_role,
    axis_spec_from_payload,
    axis_spec_to_payload,
    axis_world_span,
    clamp_index,
    derive_current_step,
    derive_axis_labels,
    derive_displayed,
    derive_margins,
    derive_order,
    fabricate_axis_spec,
    margin_span,
    steps_to_world,
    with_updated_margins,
    world_to_steps,
)

__all__ = [
    "AxisExtent",
    "AxisRole",
    "AxisSpec",
    "WorldSpan",
    "axis_by_index",
    "axis_by_label",
    "axis_role",
    "axis_spec_from_payload",
    "axis_spec_to_payload",
    "axis_world_span",
    "clamp_index",
    "derive_current_step",
    "derive_axis_labels",
    "derive_displayed",
    "derive_margins",
    "derive_order",
    "fabricate_axis_spec",
    "margin_span",
    "steps_to_world",
    "with_updated_margins",
    "world_to_steps",
]
